# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.CharField(default=b'', max_length=100, unique=True)),
                ('date_posted', models.CharField(max_length=10)),
                ('time_posted', models.CharField(default=b'', max_length=4)),
                ('text', models.CharField(default=b'', max_length=5000)),
                ('review', models.BooleanField(default=False)),
                ('polarity', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.CharField(default=b'', max_length=100, unique=True)),
                ('text', models.CharField(default=b'', max_length=5000)),
                ('date_posted', models.CharField(default=b'', max_length=10)),
                ('time_posted', models.CharField(default=b'', max_length=10)),
                ('request', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrustRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.BooleanField(default=False)),
                ('fb_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('trust', models.ManyToManyField(through='reviews.TrustRelation', to='reviews.User')),
            ],
        ),
        migrations.AddField(
            model_name='trustrelation',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_by', to='reviews.User'),
        ),
        migrations.AddField(
            model_name='trustrelation',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusts', to='reviews.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_authored', to='reviews.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='courses',
            field=models.ManyToManyField(to='reviews.Course'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='posts_liked', to='reviews.User'),
        ),
        migrations.AddField(
            model_name='course',
            name='discipline',
            field=models.ManyToManyField(related_name='Discipline', to='reviews.Discipline'),
        ),
        migrations.AddField(
            model_name='course',
            name='theme',
            field=models.ManyToManyField(to='reviews.Theme'),
        ),
        migrations.AddField(
            model_name='course',
            name='track',
            field=models.ManyToManyField(to='reviews.Track'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_authored', to='reviews.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ManyToManyField(to='reviews.Course'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='comments_liked', to='reviews.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Post'),
        ),
    ]
