# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='course',
            new_name='courses',
        ),
    ]
