# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.FloatField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_by', to='reviews.User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusts', to='reviews.User')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='polarity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.CharField(default=b'', max_length=5000),
        ),
        migrations.AddField(
            model_name='user',
            name='trust',
            field=models.ManyToManyField(through='reviews.TrustRelation', to='reviews.User'),
        ),
    ]
