# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 10:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20171207_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_id', models.CharField(max_length=100)),
                ('date_posted', models.CharField(max_length=10)),
                ('text', models.CharField(default=b'', max_length=5000)),
                ('review', models.BooleanField(default=False)),
                ('polarity', models.FloatField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.User')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Course')),
                ('likes', models.ManyToManyField(related_name='liked', to='reviews.User')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.User')),
                ('courses', models.ManyToManyField(to='reviews.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='course',
        ),
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Post'),
        ),
    ]
