# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20171221_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='polarity',
        ),
        migrations.AddField(
            model_name='comment',
            name='polarity_gs',
            field=models.FloatField(default=-2),
        ),
        migrations.AddField(
            model_name='comment',
            name='polarity_predicted',
            field=models.FloatField(default=-2),
        ),
    ]
