# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20171221_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='polarity_gs',
            field=models.IntegerField(default=-2),
        ),
        migrations.AlterField(
            model_name='comment',
            name='polarity_predicted',
            field=models.IntegerField(default=-2),
        ),
    ]
