# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_user_likes_per_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Discipline')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='reviews_written_in',
            field=models.ManyToManyField(through='reviews.NumberOfReviews', to='reviews.Discipline'),
        ),
    ]
