# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-22 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_comment_quality_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='likes_per_review',
            field=models.FloatField(default=0),
        ),
    ]
