# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20171208_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time_posted',
            field=models.CharField(default=b'', max_length=4),
        ),
        migrations.AddField(
            model_name='post',
            name='date_posted',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='fb_id',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='posts_liked', to='reviews.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(default=b'', max_length=5000),
        ),
        migrations.AddField(
            model_name='post',
            name='time_posted',
            field=models.CharField(default=b'', max_length=10),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_authored', to='reviews.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='fb_id',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(related_name='comments_liked', to='reviews.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_authored', to='reviews.User'),
        ),
    ]
