# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20171208_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='course',
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ManyToManyField(to='reviews.Course'),
        ),
    ]
