# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-08 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20171208_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='course',
        ),
    ]
